---
  - name: add TreasureData repo
    template: src=templates/td.repo dest=/etc/yum.repos.d/td.repo owner=root group=root mode=0644
    register: tdrepo
    when: ansible_distribution_major_version == "6" and install_fluentd == "yes"

  - name: install td GPG key
    rpm_key: key=http://packages.treasuredata.com/GPG-KEY-td-agent state=present
    when: ansible_distribution_major_version == "6" and install_fluentd == "yes"

  - name: install fluentd 
    yum: "pkg=td-agent state=installed"
    when: ansible_distribution_major_version == "6" and install_fluentd == "yes"

#  - name: install rubygems (for fluentd plugins) - not needed?
#    yum: "pkg=rubygems state=installed"

  - name: install fluentd plugins
    command: td-agent-gem install fluent-plugin-elasticsearch
    when: ansible_distribution_major_version == "6" and install_fluentd == "yes"

  - name: add td-agent config file
    template: src=templates/td-agent.conf dest=/etc/td-agent/td-agent.conf owner=root group=root mode=0644
    when: ansible_distribution_major_version == "6" and install_fluentd == "yes"

  - name: enable services on boot
    service: name=td-agent enabled=yes state=started
    when: ansible_distribution_major_version == "6" and install_fluentd == "yes"
