---
#  - name: update all packages first
#    yum: pkg=* state=latest

  - name: add logstash repo
    template: src=templates/logstash.repo.j2 dest=/etc/yum.repos.d/logstash.repo owner=root group=root mode=0644
    register: logstashrepo
    when: ansible_distribution_major_version == "6" and add_logstash_repofile == "yes"

  - name: install software from logstash repo
    # If we set state=latest this takes a long time to run.
    yum: "pkg={{item}} state=installed"
    with_items: programs_to_install

  - name: enable services on boot
    service: name={{item}} enabled=yes
    with_items: programs_on_boot

# Here we could add some templates for logstash config
# Also logstash -t (config test) can be used to verify the config.
