---
  - name: skip extracting files if this version already installed
    stat: path={{ kibana3_path }}
    tags: kibana3
    register: kibana3path

  - name: copy in and unpack kibana3
    unarchive: src=templates/kibana3-releases//kibana-{{ kibana_version }}.tar.gz dest=/var/www/html/
    tags: kibana3
    when: ansible_distribution_major_version == "6" and use_kibana3_httpd == true and kibana3path.stat.exists == False

  - name: symlink /var/www/html/demo-kibana3 to current kibana version
    file: src={{ kibana3_path }} dest={{ kibana3_symlink }} state=link
    tags: kibana3
    when: ansible_distribution_major_version == "6" and use_kibana3_httpd == true

  - name: send in kibana3's config.js
    template: src={{ kibana_config_js }} dest={{ kibana3_symlink }}/config.js owner=root group=root mode=0644
    tags: kibana3
    when: ansible_distribution_major_version == "6" and use_kibana3_httpd == true

  - name: add modified kibana3 default dashboards that talk to a specific index
    template: src=templates/kibana3-dashboards/{{ item }} dest={{ kibana3_symlink }}/app/dashboards/{{item}} owner=root group=apache mode=0644
    tags: kibana3
    with_items: kibana_dashboards
    when: ansible_distribution_major_version == "6" and use_kibana3_httpd == true
