
---

kibana4_ldap: False

AuthName: "CSC Password"
AuthLDAPBindDN: "uid=username,cn=users,dc=example,dc=com"
AuthLDAPBindPassword: "changeme"
AuthLDAPURL: 
   - { name: "group1", uri: "ldaps://ldap1.example.com/ou=Users,dc=example,dc=com?uid??(ou=Mracketing)" }
   - { name: "group2", uri: "ldaps://ldap1.example.com/ou=Users,dc=example,dc=com?uid??(ou=Fninance)" }
   - { name: "group3", uri: "ldaps://ldap1.example.com/ou=Users,dc=example,dc=com?uid??(memberOf=ou=Users,dc=example,dc=com)" }
# AuthLDAPURL - group1 and group2 are hard coded in the httpd-logstash.conf.j2 template
# # require_users - a space separated list - if not set then Require valid-user
require_users: ""
#
# # This sets up SSLEngine in httpd.conf
kibana4_https: True

# for rrsync users
admingroup: "rrsyncgroup"
adminshell: "/bin/bash"
adminkeyoptions: 'command="/usr/local/bin/rrsync /data/rrsync",no-agent-forwarding,no-port-forwarding,no-pty,no-user-rc,no-X11-forwarding'
adminusers:
  - {name: rsync1, state: 'present', uid: 6001, groups: "{{admingroup}}", shell: "{{adminshell}}", pubkey: "ssh-rsa KEY user@example.com", options: "{{ adminkeyoptions }}" }
adminremove_passwords: false
admin_sudoers: False
