---
# This playbook is for ELK on RHEL6(and maybe RHEL7 too) based systems. 
# Used by CSC.fi during 2015. 
# Sources: https://github.com/Traackr/ansible-elasticsearch
# All roles in here are meant to be re-playable and should be considered "safe".
# Many host specific things inside configs etc..
# Written by Johan Guldmyr
#
# export ANSIBLE_HOSTS=$HOME/ansible-hosts
# cat $ANSIBLE_HOSTS:
#[ELK]
#IP_ADDRESS_HERE ansible_ssh_user=cloud-user
# ansible-playbook setup.yml

##########

 - name: configuring all the common services
   hosts: ELK
   sudo: yes
   vars:
     programs_to_install:
       - java-1.8.0-openjdk
       - nc
       - nfs-utils
       - dstat
       - python-httplib2
       - git
       - openldap-clients
     programs_on_boot:
       - sshd
       - ntpd
     bshell: "/bin/bash"
     moregroups: esbackup
     esuser:
       - { name: elasticsearch, uid: 498, group: elasticsearch, groups: "{{moregroups}}", shell: "{{bshell}}" }
     lsuser:
       - { name: logstash, groups: "{{moregroups}}" }
     cscgroups:
       - { name: csc, gid: 101 }
       - { name: elasticsearch, gid: 201 }
       - { name: esbackup, gid: 54444 }
     add_es_repofile: "yes"
     add_es_repogpgkey: "yes"
     install_es_plugins: "yes"
     add_logstash_user: "no"
   vars_files:
     - roles/ansible-elasticsearch/defaults/main.yml
     - roles/ansible-elasticsearch/vars/my-vars.yml
      
   roles:
     - {role: ELK, tags: [ 'elasticsearch' ] }
     - {role: selinux-permissive, tags: [ 'selinux' ] }
     - {role: ansible-elasticsearch, tags: [ 'elasticsearch' ] }

##########

 - name: httpd, kibana + logstash
   hosts: ELK
   sudo: yes
   vars:
     elasticsearch_index_base: "demo"
     esb: "{{ elasticsearch_index_base }}"
     add_logstash_repofile: True
     logstash_version: "1.4"
     logstashuser: "LS_USER=logstash"
     logstashgroup: "LS_GROUP=csc"
     kibana_elasticsearch_port: "80"
     es_http_port: "9199"
     kibana_config_js: "templates/kibana-demo-config.js.j2"
     use_kibana3_httpd: true
     kibana_version: "3.1.2"
     kibana3_path: "/var/www/html/kibana-{{ kibana_version }}"
     kibana3_symlink: "/var/www/html/demo-kibana"
     kibana_interval: "day"
     kibana_pattern: "[demo-]YYYY.MM.DD"
     kibana_default: "[demo-]YYYY.MM.DD"
     kibana_dashboards:
      - "blank.json"
      - "README_MANAGED_BY_ANSIBLE.txt"
      - "guided.json"
      - "noted.json"
      - "logstash.json"
     use_kibana4_httpd: true
     kibana4_version: "4.1.2-linux-x64"
     kibana4_path: "/opt/kibana-{{ kibana4_version }}"
     kibana4_symlink: "/opt/kibana4"
     kibana4_config_yml: "templates/kibana4-demo-config.yml.j2"
     kibana4_init_script: "templates/kibana4-demo-logstash-web.init"
     # kibana4_https controls apache2's SSLEngine config 
     kibana4_https: "on"
     kibana4_ldap: True
     install_fluentd: "yes"
#       set logstash_prod_example to yes to configure logstash with redis and rsyslog input
     logstash_prod_example: True
#     kibana4_cname: "vm0444.kaj.pouta.csc.fi"
   # secrets.yml contains binddn, password, search bases for the LDAP
   # can be copied from roles/ansible-logstash/defaults/main.yml
   vars_files: 
     - secrets.yml
   roles:
     - {role: ansible-role-logstash, tags: [ 'logstash' ] }
     - {role: ansible-kibana3, tags: [ 'kibana', 'kibana3' ] }
     - {role: ansible-kibana4, tags: [ 'kibana', 'kibana4' ] }
     - {role: ansible-elk-httpd, tags: [ 'kibana', 'httpd' ] }
     - {role: ansible-elasticsearch-demo-event, tags: [ 'esput' ] }
     - {role: ansible-fluentd, tags: [ 'fluentd' ] }
