---
# This playbook is for ELK on RHEL6(and maybe RHEL7 too) based systems. 
# Used by CSC.fi during 2015. 
# Sources: https://github.com/Traackr/ansible-elasticsearch
# All roles in here are meant to be re-playable and should be considered "safe".
# Written by Johan Guldmyr

##########

 - name: configuring all the common services
   hosts: ELK
   sudo: yes
   vars_files:
     - roles/ansible-role-elasticsearch/defaults/main.yml
     - roles/ansible-role-elasticsearch/vars/my-vars.yml
      
   roles:
     - {role: ansible-role-elk, tags: [ 'elasticsearch' ] }
     - {role: ansible-role-selinux, tags: [ 'selinux' ] }
     - {role: ansible-role-elasticsearch, tags: [ 'elasticsearch' ] }

##########

 - name: httpd, kibana + logstash
   hosts: ELK
   sudo: yes
   vars:
   # secrets.yml contains binddn, password, search bases for the LDAP
   # can be copied from roles/ansible-logstash/defaults/main.yml
   vars_files: 
     - secrets.yml
   roles:
     - {role: ansible-role-logstash-demo, tags: [ 'logstash' ] }
     - {role: ansible-role-kibana4, tags: [ 'kibana', 'kibana4' ] }
     - {role: ansible-role-elk-httpd, tags: [ 'kibana', 'httpd' ] }
     - {role: ansible-role-elasticsearch-demo-event, tags: [ 'esput' ] }
     - {role: ansible-role-fluentd, tags: [ 'fluentd' ] }
     - {role: ansible-role-rrsync, tags: [ 'rrsync' ] }
     - {role: ansible-role-users, tags: [ 'rrsync', 'users' ] }
