---

elasticsearch_curator_cron_jobs:
- {
  name: "elasticsearch-curator",
  job: "/bin/curator --config /etc/curator/curator.yml /etc/curator/action.yml",
  minute: 0,
  hour: 1,
  user: root,
  cron_file: "curator"
}

# elasticsearch-curator version 4 action file
elasticsearch_curator_actions: |
 actions:
  2:
    action: close
    description: >-
      Close indices older than 33 days (based on index name), for demo-
      prefixed indices.
    options:
      delete_aliases: True
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: demo-
      exclude:
    - filtertype: kibana
      exclude: True
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 33
      exclude:
  3:
    action: delete_indices
    description: >-
      Delete indices older than 90 days (based on index name), for demo-
      prefixed indices.
    options:
      timeout_override:
      continue_if_exception: False
      disable_action: False
    filters:
    - filtertype: pattern
      kind: prefix
      value: demo-
      exclude:
    - filtertype: kibana
      exclude: True
    - filtertype: age
      source: name
      direction: older
      timestring: '%Y.%m.%d'
      unit: days
      unit_count: 90
      exclude:
 
